version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:8.0
    container_name: bento-box-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: bento-box
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - bento-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/bento-box --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Backend API (Node.js/Express)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: bento-box-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://mongodb:27017/bento-box
      JWT_SECRET: ${JWT_SECRET:-seu-secret-jwt-aqui-mude-em-producao}
      UPLOAD_DIR: /app/uploads
    ports:
      - '3001:3001'
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - bento-network
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3001/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend (Angular + Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: bento-box-frontend
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - bento-network
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost/']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

# Volumes persistentes
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  uploads_data:
    driver: local

# Network para comunicação entre containers
networks:
  bento-network:
    driver: bridge
